[package]
name = "metrics-opentelemetry"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
tako-rs = { path = "../..", features = ["metrics-opentelemetry"] }
tokio = { version = "1.45.1", features = ["full"] }
